name: Build & Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 8.0.x
      - name: Restore
        run: dotnet restore Steeltype.QRCoderLite.sln
      - name: Build
        run: dotnet build Steeltype.QRCoderLite.sln -c Release --no-restore
      - name: Test
        run: dotnet test Steeltype.QRCoderLite.sln -c Release --no-build --logger "console;verbosity=normal"
